Base:
  RunMode: "debug"
  HttpPort: 1926

App:
  AppID: "id"
  AppSecret: "pwd"

  ManagerID: "3210100000"
	KeyWord:   "借用物品"
	MAX_MONEY: 100.0

Mongo: 
  User: "admin"
  Pwd: "123456"
  Host: "localhost"
  Port: 27017
  DBName: "goodsman"
